server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: root
  application:
    name: order
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: entity
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    register-with-eureka: true
    service-url:
      # 注意这里填写其他Eureka服务器的地址，不用写自己的
      defaultZone: http://localhost:9001/eureka
feign:
  hystrix:
    enabled: true