spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #- id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
         # uri: http://localhost:9092   #匹配后提供服务的路由地址
          #predicates:
            #- Path=/payment/query/** #断言,路径相匹配的进行路由
        - id: payment_route2 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://payment   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/query/** #断言,路径相匹配的进行路由
    #断言,路径相匹配的进行路由

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
      username: root
      password: root
  application:
      name: gateway
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: entity
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9001/eureka
server:
  port: 8001
